### PR TITLE
Use escaped variants of _e() and __()

### PR DESCRIPTION
**Pull request by cfg**
Use escaped variants of `_e()` and `__()`

### CODE REVIEW

**Comment by GaryJones** [comment]
@mboynes @cfg Is there any reason this wasn't moved forward? It would cut down on a fair number of the PHPCS Errors when scanning with the WPCS / VIP Coding Standards.

**Comment by mboynes** [comment]
No reason at all, I'll make it happen, along with a full pass to make WPCS pass. Thanks for poking at it @GaryJones!

**Comment by GaryJones** [comment]
Thanks! If you could make the plugin the VIPCS `WordPress-VIP-Go` standard as well, that would wonderful 👍

**Comment by mboynes** [comment]
Will do! The work is queued up, I think someone will probably get to it today.

**Pull request merged**
